name: Pyrotechnician
author: AgentK
version: 0.1-SNAPSHOT
main: com.araeosia.pyrotechnician.Pyrotechnician
depend: [Citizens]
softdepend: [Vault]
commands:
  pyro:
    description: General Pyrotechnician command.
    usage: /<command>